# Generated by Django 4.0.1 on 2022-01-27 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('expected_amount', models.IntegerField(default=0)),
                ('amount_raised', models.IntegerField(default=0)),
                ('donation_count', models.IntegerField(default=0)),
                ('owner_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[(0, 'Open'), (1, 'Ongoing'), (2, 'Closed')], max_length=100)),
                ('category', models.CharField(choices=[(0, 'Healthcare'), (1, 'Animals'), (2, 'Art and Culture'), (3, 'Community Development'), (4, 'Environment'), (5, 'Education'), (6, 'Human Services'), (7, 'Religion')], max_length=200)),
                ('imageUrl', models.URLField(max_length=1000)),
                ('state', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Big')], max_length=50)),
            ],
            options={
                'verbose_name': 'Drive',
                'verbose_name_plural': 'Drives',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(0, 'Individual'), (1, 'Organisation')], max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=20)),
                ('donation_count', models.IntegerField(default=0)),
                ('amount_donated', models.IntegerField(default=0)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[(0, 'Female'), (1, 'Male'), (2, 'Others')], max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Donated On')),
                ('userId', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive', to='myApp.drive')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
